name: Build Simulator🧪

on:
  workflow_dispatch: 
    inputs:
      targetPlatform:
        description: 'Target Platform'
        required: true
        default: 'WebGL'
        type: choice
        options:
          - WebGL
          - StandaloneWindows64
          - StandaloneLinux64
      runsOnServer:
        description: 'Runner Server'
        required: true
        default: 'self-hosted'
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
          - windows-2019

jobs:
  checklicense:
    name: Check for UNITY_LICENSE in GitHub Secrets
    runs-on: ${{ inputs.runsOnServer }} 
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether unity activation requests should be done
        id: checklicense_job
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
            echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
            export is_unity_license_set="${{ env.UNITY_LICENSE != '' }}"
            echo "is_unity_license_set=$is_unity_license_set" >> $GITHUB_OUTPUT
  activation:
    needs: checklicense
    if: needs.checklicense.outputs.is_unity_license_set == 'false'
    name: Request manual activation file 🔑
    runs-on: ${{ inputs.runsOnServer }} 
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  buildForAllSupportedPlatforms:    
    needs: checklicense
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ inputs.runsOnServer }} 
    strategy:
            fail-fast: false
            matrix:
                targetPlatform: 
                 - ${{ inputs.targetPlatform }} 
                
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Generate versioning
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           NEW_VERSION=$(npx semantic-release --dry-run | grep "next release version" | awk '{print $4}')
           echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      
      - name: Update Unity Project Version
        run: |
          echo "Updating Unity project version to ${{ env.NEW_VERSION }}"
          sed -i "s/bundleVersion: .*/bundleVersion: ${{ env.NEW_VERSION }}/" ProjectSettings/ProjectVersion.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ProjectSettings/ProjectVersion.txt
          git commit -m "chore: update Unity project version to ${{ env.NEW_VERSION }} [skip ci]"
          git push

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
  #     - name: Run tests
  #      uses: game-ci/unity-test-runner@v4
  #      env:
  #        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #      with:
  #       githubToken: ${{ secrets.ACCESS_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: BuildBuild-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
